# Generated by Django 3.2.8 on 2021-10-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=11)),
                ('origin', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=99)),
                ('status', models.CharField(choices=[('cold', 'COLD'), ('in contact', 'IN CONTACT'), ('appointment set', 'APPOINTMENT SET'), ('offer made', 'OFFER MADE')], default='cold', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
