# Generated by Django 3.2.8 on 2021-10-27 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_call_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('other', 'OTHER'), ('single family', 'SINGLE FAMILY'), ('commercial', 'COMMERCIAL'), ('duplex', 'DUPLEX'), ('triplex', 'TRIPLEX'), ('multiplex', 'MULTIPLEX'), ('lot/land', 'LOT/LAND')], default='other', max_length=500),
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('call', 'CALL'), ('text', 'TEXT'), ('email', 'EMAIL'), ('internal note', 'INTERNAL NOTE'), ('offer', 'OFFER'), ('bad number', 'BAD NUMBER'), ('bad email', 'BAD EMAIL'), ('do not contact', 'DO NOT CONTACT')], default='internal note', max_length=500)),
                ('note', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='the_call_list.property')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
