# Generated by Django 3.2.8 on 2021-10-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_call_list', '0002_auto_20211027_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('Call', 'CALL'), ('Text', 'TEXT'), ('Email', 'EMAIL'), ('Internal Note', 'INTERNAL NOTE'), ('Offer', 'OFFER'), ('Bad Number', 'BAD NUMBER'), ('Bad Email', 'BAD EMAIL'), ('Do Not Contact', 'DO NOT CONTACT')], default='Internal Note', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Other', 'OTHER'), ('Single Family', 'SINGLE FAMILY'), ('Commercial', 'COMMERCIAL'), ('Duplex', 'DUPLEX'), ('Triplex', 'TRIPLEX'), ('Multiplex', 'MULTIPLEX'), ('Lot/Land', 'LOT/LAND')], default='Other', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Cold', 'COLD'), ('In Contact', 'IN CONTACT'), ('Appointment Set', 'APPOINTMENT SET'), ('Offer Made', 'OFFER MADE')], default='Cold', max_length=500),
        ),
    ]
