# Generated by Django 3.2.8 on 2021-10-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_call_list', '0003_auto_20211027_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('Call', 'CALL'), ('Text', 'TEXT'), ('Email', 'EMAIL'), ('Internal Note', 'INTERNAL NOTE'), ('Offer', 'OFFER'), ('Voicemail', 'VOICEMAIL'), ('Bad Number', 'BAD NUMBER'), ('Bad Email', 'BAD EMAIL'), ('Do Not Contact', 'DO NOT CONTACT')], default='Internal Note', max_length=500),
        ),
    ]
