# Generated by Django 3.2.8 on 2021-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_call_list', '0006_alter_property_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='creator',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Cold', 'COLD'), ('In Contact', 'IN CONTACT'), ('nurture', 'NURTURE'), ('Appointment Set', 'APPOINTMENT SET'), ('Offer Made', 'OFFER MADE')], default='Cold', max_length=500),
        ),
    ]
