# Generated by Django 3.2.8 on 2021-11-09 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_call_list', '0009_auto_20211109_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='lessons',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
